### ISSUE TITLE
build fail if the folder content exists

### ISSUE THREAD

**Issue by marilenadaquino** [marilenadaquino/actions#3]
If the folder `content` does not exist, the action fetches the repos correctly and checks out the md files.

If the folder exists (e.g. when running a second time) it gives a fatal error in `git ls-tree`. The fact is that, in this case, it checks for the current tree and **not the tree of the remote repo**

**Comment by marilenadaquino** [comment]
Errors: 
[log](https://github.com/marilenadaquino/actions/actions/runs/3321368465) when running the second time. It says the version number is wrong (because it looks for the tag, e.g. "v0.1.1" of *this* repo)

**Comment by marilenadaquino** [comment]
temporary fix with #[ed98fbb](https://github.com/marilenadaquino/actions/commit/ed98fbb0af5ba001d86d2224d2938d31aff23fbc)

remove the folder `content` everytime before fetching repos
@enridaga

**Comment by enridaga** [comment]
This is fixed in https://github.com/marilenadaquino/actions/commit/5fa4538cf76cc55f19f8e6350f234f0336162f4f

Another problem was that the process was exiting when trying to commit with no changes, solved now.

**Comment by enridaga** [comment]
The process should now complete successfully, creating content when missing and committing to the repo.
